"""phase3 workflows realtime

Revision ID: 20260716_0003
Revises: 20260716_0002
Create Date: 2026-07-16 10:53:17.716164
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260716_0003"
down_revision: str | None = "20260716_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    connection = op.get_bind()
    permissions = {
        "sla:manage": "Manage business calendars and SLA policies",
        "notification:read": "Read personal notifications",
    }
    for code, description in permissions.items():
        connection.execute(
            sa.text(
                "INSERT INTO permissions (id, code, description) "
                "VALUES (gen_random_uuid(), :code, :description) ON CONFLICT (code) DO NOTHING"
            ),
            {"code": code, "description": description},
        )
    connection.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT r.id, p.id FROM roles r CROSS JOIN permissions p "
            "WHERE r.name = 'Organisation Admin' AND p.code = ANY(:codes) "
            "ON CONFLICT DO NOTHING"
        ),
        {"codes": list(permissions)},
    )
    connection.execute(
        sa.text(
            "INSERT INTO role_permissions (role_id, permission_id) "
            "SELECT r.id, p.id FROM roles r CROSS JOIN permissions p "
            "WHERE r.name IN ('Agent', 'Requester', 'Auditor') "
            "AND p.code = 'notification:read' ON CONFLICT DO NOTHING"
        )
    )
    with op.get_context().autocommit_block():
        for value in ("ACTIVE", "PAUSED", "WARNING", "BREACHED", "COMPLETED"):
            op.execute(f"ALTER TYPE sla_state ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_calendars",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("weekly_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_business_calendars_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_calendars")),
        sa.UniqueConstraint(
            "organisation_id", "name", name=op.f("uq_business_calendars_organisation_id")
        ),
    )
    op.create_index(
        op.f("ix_business_calendars_organisation_id"),
        "business_calendars",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "outbox_records",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "DELIVERED", "FAILED", name="outbox_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_outbox_records_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_records")),
        sa.UniqueConstraint(
            "organisation_id", "dedupe_key", name=op.f("uq_outbox_records_organisation_id")
        ),
    )
    op.create_index(
        "ix_outbox_claim", "outbox_records", ["status", "available_at", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_records_organisation_id"),
        "outbox_records",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "calendar_holidays",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["business_calendars.id"],
            name=op.f("fk_calendar_holidays_calendar_id_business_calendars"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_calendar_holidays_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_holidays")),
        sa.UniqueConstraint(
            "organisation_id",
            "calendar_id",
            "holiday_date",
            name=op.f("uq_calendar_holidays_organisation_id"),
        ),
    )
    op.create_index(
        op.f("ix_calendar_holidays_calendar_id"), "calendar_holidays", ["calendar_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_holidays_organisation_id"),
        "calendar_holidays",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("outbox_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=40), nullable=False),
        sa.Column("recipient", sa.String(length=320), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "SENT", "FAILED", name="delivery_status"), nullable=False
        ),
        sa.Column("provider_reference", sa.String(length=200), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_delivery_attempts_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["outbox_id"],
            ["outbox_records.id"],
            name=op.f("fk_delivery_attempts_outbox_id_outbox_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_attempts")),
        sa.UniqueConstraint(
            "outbox_id",
            "channel",
            "recipient",
            "attempt_number",
            name=op.f("uq_delivery_attempts_outbox_id"),
        ),
    )
    op.create_index(
        op.f("ix_delivery_attempts_organisation_id"),
        "delivery_attempts",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_outbox_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_notifications_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_outbox_id"],
            ["outbox_records.id"],
            name=op.f("fk_notifications_source_outbox_id_outbox_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint(
            "organisation_id",
            "user_id",
            "source_outbox_id",
            name=op.f("uq_notifications_organisation_id"),
        ),
    )
    op.create_index(
        "ix_notifications_user_created",
        "notifications",
        ["organisation_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "sla_policies",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="ticket_priority",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("first_response_minutes", sa.Integer(), nullable=False),
        sa.Column("resolution_minutes", sa.Integer(), nullable=False),
        sa.Column("warning_percent", sa.Integer(), nullable=False),
        sa.Column("pause_on_waiting", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "first_response_minutes > 0", name=op.f("ck_sla_policies_positive_first_response")
        ),
        sa.CheckConstraint(
            "resolution_minutes >= first_response_minutes",
            name=op.f("ck_sla_policies_valid_resolution"),
        ),
        sa.CheckConstraint(
            "warning_percent BETWEEN 1 AND 99", name=op.f("ck_sla_policies_valid_warning_percent")
        ),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["business_calendars.id"],
            name=op.f("fk_sla_policies_calendar_id_business_calendars"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
            name=op.f("fk_sla_policies_category_id_service_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_sla_policies_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sla_policies")),
        sa.UniqueConstraint(
            "organisation_id",
            "category_id",
            "priority",
            name=op.f("uq_sla_policies_organisation_id"),
        ),
    )
    op.create_index(
        op.f("ix_sla_policies_category_id"), "sla_policies", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_sla_policies_organisation_id"), "sla_policies", ["organisation_id"], unique=False
    )
    op.create_index(
        "ix_sla_policy_lookup",
        "sla_policies",
        ["organisation_id", "category_id", "priority", "is_active"],
        unique=False,
    )
    op.create_table(
        "ticket_slas",
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM(
                "NOT_STARTED",
                "ACTIVE",
                "PAUSED",
                "WARNING",
                "BREACHED",
                "COMPLETED",
                name="sla_state",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_response_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accumulated_pause_seconds", sa.Integer(), nullable=False),
        sa.Column("warning_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("breached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workflow_id", sa.String(length=200), nullable=False),
        sa.Column("workflow_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "accumulated_pause_seconds >= 0", name=op.f("ck_ticket_slas_nonnegative_pause")
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
            name=op.f("fk_ticket_slas_organisation_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["sla_policies.id"],
            name=op.f("fk_ticket_slas_policy_id_sla_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ticket_slas_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_slas")),
        sa.UniqueConstraint(
            "organisation_id", "ticket_id", name=op.f("uq_ticket_slas_organisation_id")
        ),
        sa.UniqueConstraint("ticket_id", name=op.f("uq_ticket_slas_ticket_id")),
        sa.UniqueConstraint("workflow_id", name=op.f("uq_ticket_slas_workflow_id")),
    )
    op.create_index(
        "ix_ticket_slas_due",
        "ticket_slas",
        ["organisation_id", "state", "resolution_deadline"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_slas_organisation_id"), "ticket_slas", ["organisation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_slas_organisation_id"), table_name="ticket_slas")
    op.drop_index("ix_ticket_slas_due", table_name="ticket_slas")
    op.drop_table("ticket_slas")
    op.drop_index("ix_sla_policy_lookup", table_name="sla_policies")
    op.drop_index(op.f("ix_sla_policies_organisation_id"), table_name="sla_policies")
    op.drop_index(op.f("ix_sla_policies_category_id"), table_name="sla_policies")
    op.drop_table("sla_policies")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_delivery_attempts_organisation_id"), table_name="delivery_attempts")
    op.drop_table("delivery_attempts")
    op.drop_index(op.f("ix_calendar_holidays_organisation_id"), table_name="calendar_holidays")
    op.drop_index(op.f("ix_calendar_holidays_calendar_id"), table_name="calendar_holidays")
    op.drop_table("calendar_holidays")
    op.drop_index(op.f("ix_outbox_records_organisation_id"), table_name="outbox_records")
    op.drop_index("ix_outbox_claim", table_name="outbox_records")
    op.drop_table("outbox_records")
    op.drop_index(op.f("ix_business_calendars_organisation_id"), table_name="business_calendars")
    op.drop_table("business_calendars")
    op.execute("UPDATE tickets SET sla_state = 'NOT_STARTED'")
    op.execute("ALTER TABLE tickets ALTER COLUMN sla_state TYPE text USING sla_state::text")
    op.execute("DROP TYPE sla_state")
    op.execute("CREATE TYPE sla_state AS ENUM ('NOT_STARTED')")
    op.execute(
        "ALTER TABLE tickets ALTER COLUMN sla_state TYPE sla_state USING sla_state::sla_state"
    )
    op.execute("DROP TYPE IF EXISTS delivery_status")
    op.execute("DROP TYPE IF EXISTS outbox_status")
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code IN ('sla:manage', 'notification:read'))"
        )
    )
    connection.execute(
        sa.text("DELETE FROM permissions WHERE code IN ('sla:manage', 'notification:read')")
    )
    # ### end Alembic commands ###
